<?xml version="1.0" encoding="UTF-8"?>
<!--
    Document   : categories.xsl
    Created on : 8 May 2023, 11:14 pm
    Author     : Yc
    Description:
        Purpose of transformation follows.
-->
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:fo="http://www.w3.org/1999/XSL/Format">

    <xsl:template match="/">
        <html>
            <head>
                <style>
                    table {
                        border-collapse: collapse;
                        width: 100%;
                        font-family: Calibri, sans-serif;
                    }
                    th, td {
                        text-align: left;
                        padding: 8px;
                        border: 1px solid #ddd;
                    }
                    th { 
                        font-weight: bold;
                    }
                    h2,small {
                        font-family: Calibri, sans-serif;
                    }
                </style>
            </head>
            <body>
                <h2>Categories</h2>
                    <table>
                        <tr>
                          <th>Category Name</th>
                          <th>Description</th>
                        </tr>
                        <xsl:for-each select="categories/category">
                          <tr>
                            <td>
                              <xsl:value-of select="name"/>
                            </td>
                            <td>
                              <xsl:value-of select="description"/>
                            </td>
                          </tr>
                        </xsl:for-each>
                    </table>
                    <footer>
                      <small>Generated by TAR UMT Event Ticketing System</small>
                    </footer>
            </body>
        </html>
    </xsl:template>

</xsl:stylesheet>
