<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:fo="http://www.w3.org/1999/XSL/Format">

  <xsl:template match="/">
    <html>
      <head>
        <style>
          table {
            border-collapse: collapse;
            width: 100%;
            font-family: Calibri, sans-serif;
          }
          th, td {
            text-align: left;
            padding: 8px;
            border: 1px solid #ddd;
          }
          th {
            font-weight: bold;
          }
          h2,small {
            font-family: Calibri, sans-serif;
          }
        </style>
      </head>
      <body>
        <h2>Events</h2>
        <table>
          <tr>
            <th>Category</th>
            <th>Event Name</th>
            <th>Status</th>
            <th>Total Ticket</th>
            <th>Ticket Sold</th>
          </tr>
          <xsl:for-each select="events/event">
            <tr>
              <td>
                <xsl:value-of select="categoryName"/>
              </td>
              <td>
                <xsl:value-of select="name"/>
              </td>
              <td>
                <xsl:value-of select="status"/>
              </td>
              <td>
                <xsl:value-of select="totalQty"/>
              </td>
              <td>
                <xsl:value-of select="soldQty"/>
              </td>
            </tr>
          </xsl:for-each>
        </table>
        <footer>
          <small>Generated by TAR UMT Event Ticketing System</small>
        </footer>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>