<?xml version="1.0" encoding="UTF-8"?>

<!--//Author     : Ong Wi Lin-->

<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:fo="http://www.w3.org/1999/XSL/Format">

  <xsl:template match="/">
    <html>
      <head>
        <style>
          table {
            border-collapse: collapse;
            width: 100%;
            font-family: Calibri, sans-serif;
          }
          th, td {
            text-align: left;
            padding: 8px;
            border: 1px solid #ddd;
          }
          th { 
            font-weight: bold;
          }
          h2,small {
            font-family: Calibri, sans-serif;
          }
        </style>
      </head>
      <body>
        <h2>Payment Record</h2>
        <table>
          <tr>
            <th>Payment ID</th>
            <th>Payment No</th>
            <th>Booking ID</th>
            <th>Payment Type</th>
            <th>Price</th>
            <th>Created Date</th>
          </tr>
          <xsl:for-each select="payments/payment">
            <tr>
              <td>
                <xsl:value-of select="payment_id"/>
              </td>
              <td>
                <xsl:value-of select="payment_no"/>
              </td>
              <td>
                <xsl:value-of select="booking_id"/>
              </td>
              <td>
                <xsl:value-of select="payment_type"/>
              </td>
              <td>
                <xsl:value-of select="price"/>
              </td>
              <td>
                <xsl:value-of select="created_date"/>
              </td>
            </tr>
          </xsl:for-each>
        </table>
        <footer>
          <small>Generated by TAR UMT Event Ticketing System</small>
        </footer>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>